In [6]:
import numpy as np

In [8]:
arrid3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arrid3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [9]:
arrid3.ndim

3

In [20]:
np.linspace(34,112,20,dtype="int")

array([ 34,  38,  42,  46,  50,  54,  58,  62,  66,  70,  75,  79,  83,
        87,  91,  95,  99, 103, 107, 112])

In [22]:
np.linspace(50,500,91,dtype="int")

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

In [23]:
np.logspace(2,5,8)

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

In [26]:
np.random.randint(0,9,(3,3))

array([[3, 7, 8],
       [6, 2, 7],
       [8, 7, 4]])

In [28]:
np.zeros((6,6),dtype="int")

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [30]:
np.ones((4,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [31]:
np.eye(8,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [42]:
np.random.randint(0,2,6)

array([1, 0, 1, 1, 1, 1])

In [48]:
arrid4=np.random.randint(50,101,(5,2))
arrid4

array([[ 87,  89],
       [ 78,  77],
       [ 80,  77],
       [ 77,  59],
       [ 72, 100]])

In [49]:
arrid4.shape

(5, 2)

In [52]:
arrid5=np.random.randint(100,1000,(2,5,5))
arrid5

array([[[630, 805, 956, 716, 102],
        [187, 904, 652, 857, 408],
        [447, 927, 440, 848, 383],
        [873, 499, 164, 411, 524],
        [580, 781, 448, 160, 925]],

       [[445, 409, 746, 196, 244],
        [804, 985, 304, 995, 104],
        [964, 643, 678, 449, 703],
        [837, 263, 660, 870, 473],
        [639, 994, 565, 476, 104]]])

In [53]:
arrid5.ndim

3

In [54]:
arrid5.shape

(2, 5, 5)

In [56]:
arrid6=np.random.randint(0,101,10)
arrid6

array([13,  6, 78, 35, 46, 28, 90, 66, 19, 49])

In [58]:
arrid6.max()

90

In [59]:
arrid6.min()

6

In [60]:
arrid6.argmax()

6

In [61]:
arrid6.argmin()

1

In [69]:
arrid6=np.random.randint(300,500,(2,2,5))
arrid6.max()

482